GIMBLE_DIAMETER=46;
THICKNESS=1;
CENTER_DIAMETER=GIMBLE_DIAMETER/2;
CENTER_HEIGHT=28;
HOLE_DIAMETER=9;
$fn=64;

difference() {
  cylinder(r1=GIMBLE_DIAMETER/2, r2=CENTER_DIAMETER/2, h=CENTER_HEIGHT);
  cylinder(r=HOLE_DIAMETER/2, h=CENTER_HEIGHT*2);
}

